[[redirects]]
  from = "/2018/04/13-intro-to-android-platform-development.html"
  to = "/Android-platform-development"

[[redirects]]
  from = "/2019/03/24-open-letter-to-mep.html"
  to = "/Otvoreny-list-poslancom-Europskeho-parlamentu"

[[redirects]]
  from = "/2019/06/17/stopwatch-for-firefighter-competitions.html"
  to = "/Stopwatch-for-Firefighter-Competitions"

[[redirects]]
  from = "/2019/11/16/why-i-changed-my-mind-on-social-networks.html"
  to = "/Why-I-changed-my-mind-on-social-networks"

[[redirects]]
  from = "/2019/11/27/what-does-it-take-to-write-a-good-arduino-library.html"
  to = "/What-does-it-take-to-write-a-good-Arduino-library"

[[redirects]]
  from = "/2019/12/08/ci-with-arduino.html"
  to = "/Continuous-integration-with-Arduino"

[[redirects]]
  from = "/2019/12/15/our-school-system-is-antiquated-part1.html"
  to = "/Our-school-system-is-antiquated.-It's-time-for-a-change!-Part-1"

[[redirects]]
  from = "/2019/12/15/our-school-system-is-antiquated-part2.html"
  to = "/Our-school-system-is-antiquated.-It's-time-for-a-change!-Part-2"

[[redirects]]
  from = "/2019/12/15/our-school-system-is-antiquated-part3.html"
  to = "/Our-school-system-is-antiquated.-It's-time-for-a-change!-Part-3"

[[redirects]]
  from = "/2019/12/21/one-year-freelancer.html"
  to = "/2019.-The-Year-When-I-Took-The-Leap-of-Faith-and-Became-a-Freelancer"

[[redirects]]
  from = "/2019/12/25/focus-on-niche-market.html"
  to = "/A-successful-startup-Focus-on-niche-market!"

[[redirects]]
  from = "/2019/12/25/reasons-to-be-a-youtuber.html"
  to = "/Eleven-reasons-to-become-a-YouTuber-in-2020"

[[redirects]]
  from = "/2019/12/28/reasons-to-be-a-youtuber.html"
  to = "/Eleven-reasons-to-become-a-YouTuber-in-2020"

[[redirects]]
  from = "/2019/12/31/my-internet-health-story.html"
  to = "/My-Internet-Health-Story"